#!/usr/bin/env node
require('update-notifier')({pkg: require('./package.json')})
  .notify({defer: true})
var path = require('path')
var formatError = require('./bin/format-error')
var script = path.basename(process.argv[1])
require('./bin/' + script + '.js')(
  process.argv.slice(2),
  process.cwd(),
  path.join(
    require('xdg-basedir').config,
    require('./package.json').name
  ),
  process.stdin,
  process.stdout,
  process.stderr,
  function (error) {
    if (error) {
      process.stderr.write(formatError(error))
      process.exit(1)
    }
    process.exit(0)
  }
)
